
require_relative "ast/access_by_id"
require_relative "ast/constant_define"
require_relative "ast/declare_category"
require_relative "ast/declare_decorator"
require_relative "ast/declare_file"
require_relative "ast/declare_id"
require_relative "ast/declare_meme"
require_relative "ast/declare_object"
require_relative "ast/declare_string"
require_relative "ast/invoke"
require_relative "ast/local_variable_access_ambiguous"
require_relative "ast/quest"

require_relative "ast/misc"
